[build]
  publish = "."

[[redirects]]
  from = "https://www.solidfinishsolutions.co.uk/*"
  to = "https://solidfinishsolutions.co.uk/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
